[package]
name = "jira-clone"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
ellipse = "0.2.0"
itertools = "0.10.5"

[dev-dependencies]
tempfile = "3.20.0"
